language: python
python:
  - '2.7'
  - '3.6'
install:
  - sudo apt-get install -qq python-dev libxml2-dev libxmlsec1-dev
before_script:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - npm install -g jshint
  - cp travis-ci/manage.py manage.py
script:
  - pycodestyle scheduler/ --exclude=migrations,test
  - jshint scheduler/static/scheduler/js/ --verbose
  - coverage run --source=scheduler/ --omit=scheduler/migrations/* manage.py test scheduler
after_success:
  - coveralls
