sudo: required

language: python
python:
  - 3.6

services:
  - docker

os:
  - linux

env:
  global:
    - RELEASE_NAME="scheduler"
    - DJANGO_APP="scheduler"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
    - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master
    - secure: "ePpELFxQvZKsDR3Gct7/OosiG/dP8DwI28l4LzfVLbhY+fRyrC46h4VVP3R3wtwI1UVz5x8upKjyADU3/VVH3py3uTCDEGgHiHw4eOT3dFxLFv1xGZoTLfhjhjo37I/mfSjb43KKMOWqnvyO0ZzuO5je1sRGGWRvDqmhdaR/JtTLlcDB0+/WbUG/EOPqns9OiKZBTHJANXlhUurXkfBfhvAJzZzGigOhL+sgqf86BmAcr8SSI8I8O6EX8il/cBDAFpqy2mjOJkbN2cNUSP/n6QZXcNd61pBL0dpyzTxSkD9SNmpavxmsAlmL9/benff7D1G/jcLlOyOqNj+3Fqr4H8HKlMMscTzH5oMsJGOqbvFZTlwxAvnh7kxmlhXJe4tRDwMiiBHsywcXJG/C3jV00J5wsPGznHX0DwDFlDklWPIavMpbXPrBFeENSvE6yZqHqnn/qeB5S6K0u25Rbo2OEWcb5bOgaeV1IV/D2tKPiazXokwkhkgOB/XcIDwSAmrqDxM9ItxHis00iI95Dn5Uj+nZh6bSIxFk1EKofSRD9NXZG4O0QO0FEOLxK68PtyWBElOO8J+t9LuS7EtE9jzZvQG9F34Mh2v4osUvKiqF1B5g2g9B9fCki6zoK26UO9LIwJeirEclWcZ+Y2FG0G70wSX3yWRO7irKpOLD5Dlv9YE="
    - secure: "fIUitFnVv8hgPSYEYSls214Dhl3AzpYKs3JzAAlcb5vbDS0OLClSQB8i1enfydnCVK3iZn/nxOz0PCUXlgJtmBCWGl41GBqNainb1bRvNAaStN3n17JGBhaocqLItUqUrUlEtJt/FOVidM2Vn7tCm4aUMYh22SO8h7DmZoTdUfsRcIBWE33TndzF7mfyl2Ymbmha43/5kjAeX5uC5wZN1GOAXOMH+tVs6pkC9P1dbKkvK1B3O/pRmcHZ/1oFXgEdb1PecY0JdEXcKnF6eXa3eHqrWoAEy4vSeMmjeHVMZRck1BTe7qZHHW25v5wNvnxvBD1M91m/EVJzgk7v1a3mJeaiT8UJFYUq9M1QG4XlJ2JupaV6sQj2u6aU9f4BJ3uwM+X0w1pT24pejRKQ/Vdm77eI1jB8N/nwFooHFGEB4lmYYjtGsrZBY4FzLPgHwFOv6K81Vc7DmP5zHONuemGs3T2pxAwS8pKZymfXXhEyWZ6z3+pCpMXqbvbcZrF505ZPuGRULv8Drb9HrJz6D9vhdbmdAtJd5mt5EFmzo+b3WcGCqpseGgRsU6zfqSHCQ0wrE3fY87k0FSYcjEE7xOhFG5OVV8J5iELfK22DNzCY3TFGfhX/3Laal3/qrVUs1kdPx2x+Jru/TaHKod4s8FHRk0ukGFpDzQ+2DXNMRw8q4JU="
    - secure: "DgefETN9KIq89tBESM7BvT5Eh89El24HJ74UnhETH0OTtt7c7djsjLORhTpRUy2W06ZTu3o3BMQCHL3IMAsFiIC4o7dM1VxOm5P0/gUAESohC7TgfqSWuuPSx/50V8DEfTptaLRdxlqA3mTPnVSi43VW1T3YoX6l8xJ6bflHN7c/8h/WltO1KiaaEfRZHoArh4cizYUrRwrWYOWuZ2SumqZ4L39FUCxLsMrrvwfd/iMt9gir0BnZOrKDSOxACSGJQikFB9nsxncpryOhH+Kfr8sxpNc0x0BD+DNtUM+FSOyU2K8LJMW54Xy7CmuzPxlQDR50R8Q9O1iO6p9KQ3z9u0SZugH8PJsPnR9LpOGDPFC7+3EQRfUa1fdgEb0y/2GHi2DrAfDpThtloy8yDEn5UV8vgmtkMq6UqJIouZ46MC2pY3wpUq3oQP4VgrNNrkS+rnfdk91t7k6RAbDmqC6ZNakX3OhR+HSnH05i14oHxVdaQDEw68XMg6acKaViDoRRJF+ql4hhPTsbFX/x9kGqy/Rl5rUFgqEp4rCRxr7WjF/O7mIufZh9qu3Eqc04UN/8gLrK+W7n50Qc1UZYg49wGivY3I/nJIEZCrkJUkJrXn2bNF4aPLk9IGwhfv4KdnKNSwepRhJTKD5TByh1zUHeF9P2AA7EZ56IhShu5XOcbvE="

install:
  - docker build -t "$IMAGE_TAG" .

before_script:
  - pip install coverage
  - pip install coveralls

script:
  - docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev" -e "AUTH=SAML_MOCK" "$IMAGE_TAG" bash -c ". ./travis-ci/test.sh"

after_success:
  - cp /tmp/.coverage.* .
  - coverage combine
  - coveralls
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" =~ ^(develop|master)$ ]]; then
#    curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash;
#    fi

cache:
  directories:
    - "$HOME/helm"
    - "$HOME/kubeval"
