version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: SAML_MOCK BLTI_DEV
      LTI_DEVELOP_APP: course
    restart: always
    container_name: app-scheduler
    build:
      context: .
      target: app-container
    volumes:
      - ./scheduler:/app/scheduler
    ports:
      - "8000:8000"
