autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 95
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 75m
    memory: 192Mi
affinity:
   podsSpanNodes: true
ingress:
  enabled: true
  type: nginx
  tls:
    panopto-app:
      secretName: panopto-app.uw.edu-ingress-cert
      hosts:
        - panopto-app.uw.edu
  hosts:
    panopto-app:
      host: panopto-app.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
database:
  engine: postgres
  name: panopto
  hostname: scheduler-db-service
  secretName: panopto-app.uw.edu-sql-secrets
externalService:
  enabled: true
  name: scheduler-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.208
  servicePort: 5432
readiness:
  enabled: true
repo: scheduler
instance: prod
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  pushgateway:
    enabled: true
    replicaCount: 1
memcached:
  enabled: true
  replicaCount: 1
certs:
  mounted: true
  certPath: /certs/panopto-app.uw.edu.cert
  keyPath: /certs/panopto-app.uw.edu.key
  secretName: panopto-app.uw.edu-ic-certs
cronjob:
  enabled: true
  jobs:
    - name: confirm-recordings
      schedule: "5 12 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["confirm_recordings"]
environmentVariables:
  - name: ENV
    value: prod
  - name: GWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: R25_ENV
    value: PROD
  - name: CANVAS_ENV
    value: PROD
  - name: AUTH
    value: SAML BLTI
  - name: SAML_ENTITY_ID
    value: https://panopto-app.uw.edu/shibboleth
  - name: CLUSTER_CNAME
    value: panopto-app.uw.edu
  - name: PANOPTO_SERVER
    value: uw.hosted.panopto.com
externalSecrets:
  enabled: true
  secrets:
    - name: panopto-app.uw.edu-secrets
      externalKey: panopto-app/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: panopto-api-user
          property: panopto-api-user
        - name: panopto-api-app-id
          property: panopto-api-app-id
        - name: panopto-api-token
          property: panopto-api-token
        - name: blti-aes-iv
          property: blti-aes-iv
        - name: blti-aes-key
          property: blti-aes-key
        - name: canvas-account-id
          property: canvas-account-id
        - name: canvas-oauth-bearer
          property: canvas-oauth-bearer
        - name: collegenet-auth-token
          property: collegenet-auth-token
        - name: lti-consumers
          property: lti-consumers
        - name: email-host
          property: email-host
    - name: panopto-app.uw.edu-sql-secrets
      externalKey: panopto-app/prod/sql-secrets
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: panopto-app.uw.edu-ic-certs
      externalKey: panopto-app/prod/ic-certs
      data:
        - name: panopto-app.uw.edu.key
          property: key
        - name: panopto-app.uw.edu.cert
          property: cert
    - name: panopto-app.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: panopto-app.uw.edu-secrets
    secretKey: django-secret
  panoptoAPIUser:
    name: PANOPTO_API_USER
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-user
  panoptoAPIAppId:
    name: PANOPTO_API_APP_ID
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-app-id
  panoptoAPIToken:
    name: PANOPTO_API_TOKEN
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-token
  panoptoAPIBLTIAESKey:
    name: BLTI_AES_KEY
    secretName: panopto-app.uw.edu-secrets
    secretKey: blti-aes-key
  panoptoAPIBLTIAESIV:
    name: BLTI_AES_IV
    secretName: panopto-app.uw.edu-secrets
    secretKey: blti-aes-iv
  panoptoCanvasAPIOAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: panopto-app.uw.edu-secrets
    secretKey: canvas-account-id
  panoptoCanvasAPIOAuthBearer:
    name: CANVAS_OAUTH_BEARER
    secretName: panopto-app.uw.edu-secrets
    secretKey: canvas-oauth-bearer
  collegenetAPIToken:
    name: R25_BASIC_AUTH
    secretName: panopto-app.uw.edu-secrets
    secretKey: collegenet-auth-token
  panoptoLTI_CONSUMERS:
    name: LTI_CONSUMERS
    secretName: panopto-app.uw.edu-secrets
    secretKey: lti-consumers
  emailHost:
    name: EMAIL_HOST
    secretName: panopto-app.uw.edu-secrets
    secretKey: email-host
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: panopto-app.uw.edu-ic-certs
    secretKey: panopto-app.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: panopto-app.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
