autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 95
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 75m
    memory: 192Mi
affinity:
   podsSpanNodes: true
ingress:
  enabled: true
  type: nginx
  tls:
    panopto-app:
      secretName: panopto-app.uw.edu-ingress-cert
      hosts:
        - panopto-app.uw.edu
  hosts:
    panopto-app:
      host: panopto-app.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
database:
  engine: postgres
  name: panopto
  hostname: scheduler-db-service
  secretName: panopto-app.uw.edu-sql-secrets
externalService:
  enabled: true
  name: scheduler-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.208
  servicePort: 5432
readiness:
  enabled: true
repo: scheduler
instance: prod
namespace:
  enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  pushgateway:
    enabled: true
    replicaCount: 1
memcached:
  enabled: true
  replicaCount: 1
certs:
  mounted: true
  certPath: /certs/panopto-app.uw.edu.cert
  keyPath: /certs/panopto-app.uw.edu.key
  secretName: panopto-app.uw.edu-ic-certs
cronjob:
  enabled: true
  jobs:
    - name: confirm-recordings
      schedule: "5 12 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["confirm_recordings"]
environmentVariables:
  - name: ENV
    value: prod
  - name: GWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: R25_ENV
    value: PROD
  - name: CANVAS_ENV
    value: PROD
  - name: AUTH
    value: SAML BLTI
  - name: SAML_ENTITY_ID
    value: https://panopto-app.uw.edu/shibboleth
  - name: CLUSTER_CNAME
    value: panopto-app.uw.edu
  - name: PANOPTO_SERVER
    value: uw.hosted.panopto.com
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: LTI_CONFIG_DIRECTORY
    value: /lti/config
externalSecrets:
  enabled: true
  secrets:
    - name: panopto-app.uw.edu-secrets
      externalKey: panopto-app/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: panopto-api-user
          property: panopto-api-user
        - name: panopto-api-app-id
          property: panopto-api-app-id
        - name: panopto-api-token
          property: panopto-api-token
        - name: blti-aes-iv
          property: blti-aes-iv
        - name: blti-aes-key
          property: blti-aes-key
        - name: canvas-account-id
          property: canvas-account-id
        - name: canvas-oauth-bearer
          property: canvas-oauth-bearer
        - name: collegenet-auth-token
          property: collegenet-auth-token
        - name: lti-consumers
          property: lti-consumers
        - name: email-host
          property: email-host
    - name: panopto-app.uw.edu-sql-secrets
      externalKey: panopto-app/prod/sql-secrets
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: panopto-app.uw.edu-lti-keys
      externalKey: panopto-app/test/lti-keys
      data:
        - name: private-key-1.key
          property: private-key-1.key
        - name: public-key-1.key
          property: public-key-1.key
    - name: panopto-app.uw.edu-ic-certs
      externalKey: panopto-app/prod/ic-certs
      data:
        - name: panopto-app.uw.edu.key
          property: key
        - name: panopto-app.uw.edu.cert
          property: cert
    - name: panopto-app.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: panopto-app.uw.edu-secrets
    secretKey: django-secret
  panoptoAPIUser:
    name: PANOPTO_API_USER
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-user
  panoptoAPIAppId:
    name: PANOPTO_API_APP_ID
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-app-id
  panoptoAPIToken:
    name: PANOPTO_API_TOKEN
    secretName: panopto-app.uw.edu-secrets
    secretKey: panopto-api-token
  panoptoAPIBLTIAESKey:
    name: BLTI_AES_KEY
    secretName: panopto-app.uw.edu-secrets
    secretKey: blti-aes-key
  panoptoAPIBLTIAESIV:
    name: BLTI_AES_IV
    secretName: panopto-app.uw.edu-secrets
    secretKey: blti-aes-iv
  panoptoCanvasAPIOAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: panopto-app.uw.edu-secrets
    secretKey: canvas-account-id
  panoptoCanvasAPIOAuthBearer:
    name: CANVAS_OAUTH_BEARER
    secretName: panopto-app.uw.edu-secrets
    secretKey: canvas-oauth-bearer
  collegenetAPIToken:
    name: R25_BASIC_AUTH
    secretName: panopto-app.uw.edu-secrets
    secretKey: collegenet-auth-token
  panoptoLTI_CONSUMERS:
    name: LTI_CONSUMERS
    secretName: panopto-app.uw.edu-secrets
    secretKey: lti-consumers
  emailHost:
    name: EMAIL_HOST
    secretName: panopto-app.uw.edu-secrets
    secretKey: email-host
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: panopto-app.uw.edu-ic-certs
    secretKey: panopto-app.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: panopto-app.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert

mountedSecrets:
  enabled: true
  mountPath: /lti/keys
  secretName: panopto-app.uw.edu-lti-keys

podVolumes:
  lti-tool-config:
    volume:
      configMap:
        name: lti-tool-config
    mount:
      mountPath: /lti/config
    containers: [base]

configmaps:
  lti-tool-config:
    tool.json: |
      {
        "https://canvas.instructure.com": [{
          "default": true,
          "client_id": "100000000000819",
          "auth_login_url": "https://sso.canvaslms.com/api/lti/authorize_redirect",
          "auth_token_url": "https://sso.canvaslms.com/login/oauth2/token",
          "key_set": null,
          "key_set_url": "https://sso.canvaslms.com/api/lti/security/jwks",
          "private_key_file": "/lti/keys/private-key-1.key",
          "public_key_file": "/lti/keys/public-key-1.key",
          "deployment_ids": ["214645:ec62f2907b6c712911c1fd2834c835c1d1801f43",
                            "214646:70b5aaad59752acb7395dc20fbb5bd7db2cff8a7",
                            "214647:9ee81ecc3cf31cabb97c147bd1689b428f57f2c4",
                            "214648:3db27ecc1fee4f4509b301fe49040da39bd8bef4",
                            "214653:d5d70ecbfea2d269e0ef2243753a13360ef5654c",
                            "214654:822dd831b8c5ef8344cffa2fb8994ab5c9ccdea0",
                            "214655:46dd75e118d852281edb41c87284595e1d985ffd",
                            "214656:fb1724bbf63bdce8a5ed2be4c60092e0b552d89f",
                            "214657:f798da5d17ebd4b23310abe450f11c290184cc84",
                            "214658:ecd3fe95fd8ea8a5d25df8a8021a816f858c6c96",
                            "214659:3b84a298ea8f0c8082ed9ff15ba3ba8036a9bd40",
                            "214660:836b93d0eec8261988a3197e17480eb03bf6a906",
                            "214661:ad0416b4a90cd8511c4d8b53d2e7bf95d0c4cc59",
                            "214664:dd90f51b548c6a7fd44e5946c431c71097b559e6",
                            "214669:7aa8a0725d23b4928d9a1c3c3a65a34c58ac6a63",
                            "214688:536e5a261433638964a5591f41008315f434b849",
                            "214696:82ea3323587ae330766ae046461fd35c747ed747",
                            "214699:0f039f1749e78d4873d3001594ba51c12b9efebd",
                            "214702:e597806a58d81c3f955090b82707e4a6cc15862c",
                            "214703:d14a9f802ca37505f48664d35bae2a07c182a2f4",
                            "214704:7fa0ff5e705f6c9f356b00edd3b7d25f10c61d92",
                            "214705:b77fc0ce0e56b7f1a8a5b67a00b911e338fff369"]
        }]
      }
