# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('quarter', models.CharField(max_length=6)),
                ('curriculum', models.CharField(max_length=12)),
                ('number', models.CharField(max_length=3)),
                ('section', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_abbr', models.SlugField(max_length=20, unique=True)),
                ('campus_code', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecorderCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecorderCacheEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder_id', models.CharField(max_length=36)),
                ('recorder_external_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.RecorderCache')),
            ],
        ),
    ]
