# Generated by Django 3.2.16 on 2022-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200226_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_crosslisted', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('profile_name', models.CharField(max_length=32)),
                ('contact_name', models.CharField(max_length=64)),
                ('contact_email', models.CharField(max_length=128)),
                ('space_id', models.CharField(max_length=64, null=True)),
                ('space_name', models.CharField(max_length=128, null=True)),
                ('space_formal_name', models.CharField(max_length=128, null=True)),
                ('is_instruction', models.BooleanField(null=True)),
                ('is_course', models.BooleanField(null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
